apiVersion: v1
data:
  prometheus.yml: "global:\n  scrape_interval: 15s\n\nscrape_configs:\n  - job_name: 'gateway'\n    static_configs:\n      - targets: ['gateway:8000']\n  \n  - job_name: 'nlu-service'\n    static_configs:\n      - targets: ['nlu-service:8001']\n  \n  - job_name: 'orchestrator'\n    static_configs:\n      - targets: ['orchestrator-service:8004']"
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
