apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: knowledge-ingestion-service-claim1
  name: knowledge-ingestion-service-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
